name: Deploy to EC2

on:
  push:
    branches:
      - '**'  # This triggers for any branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Code to EC2 (except for main)
        run: |
          # Check if the branch is not 'main'
          if [ "${GITHUB_REF##*/}" != "main" ]; then
            echo "Deploying branch: ${GITHUB_REF##*/}"
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_HOST }} << 'EOF'
              cd /var/www/myproject
              git pull origin ${GITHUB_REF##*/}  # Pull the branch that triggered the action
          else
            echo "Skipped deployment for the main branch."
          fi 
          EOF
          
