name: Deploy to AWS EC2

on:
  push:  # This triggers on any push to any branch
    branches:
      - '**'  # Optional, just in case you want to specify all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Code to EC2
      run: |
        ssh ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          cd /var/www/myproject
          git pull origin main  # Make sure this matches the correct branch you want to pull from
          # Run additional commands if needed
          # For example: npm install, composer install, etc.
        EOF
